// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQiAEXkLKQsOMLsSVTnKRkj9cm_cKnjY',
    appId: '1:1024339062606:web:2c65a2098a6c2598e8b81f',
    messagingSenderId: '1024339062606',
    projectId: 'bike-app-f1f18',
    authDomain: 'bike-app-f1f18.firebaseapp.com',
    storageBucket: 'bike-app-f1f18.appspot.com',
    measurementId: 'G-54CPP29Y36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsudu2J9gt3b4LGoYuIHcXiZ3j93njLts',
    appId: '1:1024339062606:android:0cd77bf227f3b9c6e8b81f',
    messagingSenderId: '1024339062606',
    projectId: 'bike-app-f1f18',
    storageBucket: 'bike-app-f1f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADOFyfYItK5xy5VscnTm9_p3niNNizYe4',
    appId: '1:1024339062606:ios:5982c067c7fda593e8b81f',
    messagingSenderId: '1024339062606',
    projectId: 'bike-app-f1f18',
    storageBucket: 'bike-app-f1f18.appspot.com',
    iosBundleId: 'com.example.bikeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADOFyfYItK5xy5VscnTm9_p3niNNizYe4',
    appId: '1:1024339062606:ios:093655f619e96a28e8b81f',
    messagingSenderId: '1024339062606',
    projectId: 'bike-app-f1f18',
    storageBucket: 'bike-app-f1f18.appspot.com',
    iosBundleId: 'com.example.bikeApp.RunnerTests',
  );
}
